### ISSUE TITLE
Invalidate Cache on Project Update

### ISSUE THREAD

**Issue by bryanjnelson** [SeedCompany/cord-field#1129]
When updating the status of a Project the engagements on that same page do not currently refresh automatically with their updated status.  The cache needs to be invalidated so that the client will re-pull this data.

**Comment by CarsonF** [comment]
So there's a few ways to solve this:
1. Update the mutation to include the properties that are changing.
2. Update the properties in local cache ourselves assuming the new values.
3. Delete or invalidate the properties from the local cache that are changing.

The first is better if the field is accessible from the response schema. It doesn't require an extra http request, and doesn't assume what the new value will be. It's also easy to do since it's just adding fields to the mutation document. [Example 1](https://github.com/SeedCompany/cord-field/blob/dbdaa0029f4b64fce8a7d4cc9dd90a7c142c0b6e/src/scenes/Projects/Update/UpdateProject.graphql#L5-L5). [Example 2](https://github.com/SeedCompany/cord-field/blob/dbdaa0029f4b64fce8a7d4cc9dd90a7c142c0b6e/src/scenes/Projects/Update/UpdateProject.graphql#L5-L5).

The second is useful if it's trivial to assume the new value, we can do that without having to ask the API for it, which could speed up the mutation response. [Example 1](https://github.com/SeedCompany/cord-field/blob/dbdaa0029f4b64fce8a7d4cc9dd90a7c142c0b6e/src/scenes/Projects/Budget/ProjectBudgetRecords.tsx#L44-L51). [Example 2](https://github.com/SeedCompany/cord-field/blob/dbdaa0029f4b64fce8a7d4cc9dd90a7c142c0b6e/src/scenes/Engagement/LanguageEngagement/Create/CreateLanguageEngagement.tsx#L59-L69).

The third is useful if we don't know the new value and we can't get the value from the response schema. Invalidating the cached field allows the gql client to know to re-run the query when it is needed in the UI. This can also be useful when we aren't sure if the new value will be needed and don't want to slow down the mutation request every time.
[Example](https://github.com/SeedCompany/cord-field/blob/dbdaa0029f4b64fce8a7d4cc9dd90a7c142c0b6e/src/scenes/Projects/Update/UpdateProjectDialog.tsx#L178-L190)
