### ISSUE TITLE
QR | Progress Chart Step

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#1177]
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466483591) by [Unito](https://www.unito.io)
┆Link To Item: https://seed-company-squad.monday.com/boards/3451697530/pulses/3466483591

**Comment by sherijennings** [comment]
https://cordfield.com/progress-reports/K1JPylmxZuC

**Comment by sherijennings** [comment]
Progress for Goals 
Allow Field Partner to edit %, @sherijennings verifying values should be 0%, 25%, %0%, 75%, 100% or other
@AmyRickwartz is designing read view, will show input from field partner & upload from field project manager

**Comment by sherijennings** [comment]
Explanation of Progress
Allow user/FPM to select status of Behind/Delayed, On Schedule, Ahead of Schedule, then user will select 1 explanation from a list of reasons (15-20)
Reporting: Add fields to DOMO API? for reporting
Add text box input: Allow FPM to add additional information related to explanation of progress status 
View: Allow authorized users to view Explanation of Progress status & additional information before and after quarterly report submission. 
Allow authorized users to view explanation of progress status and text box information in Quarterly Narrative Report View
Edit, Allow authorized users to edit Explanation of Progress before and after submission

BEHIND/DELAYED
Delayed activities/activities did not occur/slow start of project
Team is being trained at start of project; they expect to catch up by end of project
Delayed hiring and/or replacement of personnel
Economic/political/civil instability or unrest
Late or delayed partner reporting
Partner organization issues: leadership/infrastructure
Health issues with team members or their families
Team member passed away
Security breach/teams in hiding
Unstable internet
Checking delayed because translation consultants not available
ON TIME
Team on track
AHEAD
Training/drafting/checking ahead of schedule
Project plan set slower to accommodate new team, and new team made good progress
Team is experienced and worked faster than anticipated
