### ISSUE TITLE
Implement "near operation file" for graphql code gen

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#182]
## Problem 
The current config has some downsides:
- The single `graphql.generated.tsx` file is getting bigger and bigger. This makes it harder to reason about and the linter gets slower and slower for every operation added & changed.
- It's hard to find the graphql definition from TS. You say "go to" in your editor to the hook/interface and it takes you to `graphql.generated.tsx` every time and you are still left wondering where the graphql src is.

## Solution
With "near operation file" configuration, every graphql file/"operation" has it's own generated file next to it. This:
- Keeps the files small, in turn keeping linting fast.
- Helps with dev navigation as the gql src is right next to the hook/interface.

https://graphql-code-generator.com/docs/presets/near-operation-file
https://graphql-code-generator.com/docs/generated-config/near-operation-file
## Expectations

- [ ] A `src/api/schema.generated.tsx` file containing our TS schema without operations
- [ ] Every other graphql file gets a `*.generated.tsx` file next to it.
  - `components/ProjectListItem/ProjectListItem.graphql`
  - `components/ProjectListItem/ProjectListItem.generated.tsx`
- [ ] If there are any gotchas found in implementation they are communicated back to me 😄

**Comment by richardgirges** [comment]
Working on this right now, I just wanted to brain dump some issues I'm running into. I'm still not done here, so all of these issues might be resolved before I send a PR:

* When a query or mutation name is changed, you're left with a lot of "leftover" `.generated` files that need manual cleaning
* `eslint fix` is waaaay too slow and spikes my CPU when it's being run on every single `.generated` file

@CarsonF - one more Q: I forgot why we did this, but what was the reason for not simply just eslintignoring all generated files?

**Comment by CarsonF** [comment]
> * When a query or mutation is created then removed, you're left with a lot of "leftover" `.generated` files that need manual cleaning

This just happens when you rename/move a file? I don't think that describes "lots". I'm ok with devs manually cleaning this. Or just renaming/moving the generated file at the same time as the graphql file.
Or am I missing something here? It's only one generated file per graphql file, right?


> * `eslint fix` is waaaay too slow and spikes my CPU when it's being run on every single `.generated` file

Does every generated file get re-created while watching? It's not incremental? That would be unfortunate. If that means that eslint it is also ran on every generated file then that's really unfortunate.
We are definitely building a case for just ignoring linting on generated files.

**Comment by richardgirges** [comment]
I think we're just getting lost in rhetoric here, but yes, "lots" perhaps wasn't the best word choice :)

What I meant to say that it creates a suboptimal developer experience when you have to be diligently aware of _any_ files your code generator has left behind, given the point of codegen is to "automate" things.  Not a huge deal-breaker though if we want to put the onus on the developer to clean up after themselves here.

The real problem with the leftover generated files is actually that it seems the behavior is inconsistent: sometimes the files are removed as expected, sometimes they remain. Still trying to figure out exactly what's going on here - will report back with more findings. 

As for the `eslint --fix` issue: after further investigation, I discovered the generated files _are_ incremental. But on initial `yarn start`, all files get generated from scratch. The result is a heavy `yarn start` process where my CPU spikes for a bit. Since this only happens on `yarn start`, I think we might be okay 👍

**Comment by CarsonF** [comment]
### Leftover files
Obv we want a good DX here. It's weird that it's inconsistent. Maybe we could have a custom process that deletes any generated files that don't have a corresponding graphql file. Would would have to take steps to ensure it's not over zealous.

It would probably also be useful to add an export for the generated file to the sibling `index.ts` file, as I'm sure there's a use case for importing those interfaces outside of the current folder.
That could be a next iteration thing.

I've been looking at the plugins though, they are pretty straight forward, so doing custom things shouldn't be that bad.

### Linting
Ok cool, that's what I was thinking. I'm fine with that for now. All of our processes are heavy when spinning up, i.e. storybook. Needing to restart the process shouldn't be that frequent. 

But I do find myself stopping the generator while rebasing because it screws it up there. Mostly, I think because it writes the file to disk and then separately writes the linting changes, so half way through that process git says hey there's changes. If it were all done in memory, writing the file should result in no changes (usually) which would be better.

Also, currently it's the same code as before just split across multiple files. I'm wondering if that makes it slower or faster for eslint. Unfortunately, I think it's slower.

**Comment by richardgirges** [comment]
Dude I think I just found the culprit behind both of the "leftover files" and "linting" issue. It was this line in the `codegen.yml`:

```yaml
  afterOneFileWrite:
    - eslint --fix
```

Changing it to `afterAllFileWrite` did it. I should've realized this from the get-go given the nature of this update (splitting one generated file into multiple). >.<

What was happening was:

* Whenever a file got deleted/moved, codegen would appropriately remove it. But because the `eslint --fix` command was already _in flight_ for that particular file, `eslint --fix` _re-wrote_ the file back to disk. What a doozy!

* Linting was waaaay faster, even on startup after this update as well. Instead of 20+ `eslint --fix` commands targeting a single file, it's now consolidated into one command

**Comment by CarsonF** [comment]
Interesting. I remember we had `afterOneFileWrite` because it passed the filename into the lint command limiting the scope of the linter to just that one file. Where `afterAllFileWrite` doesn't do that. 



> * Whenever a file got deleted/moved, codegen would appropriately remove it. But because the `eslint --fix` command was already _in flight_ for that particular file, `eslint --fix` _re-wrote_ the file back to disk. What a doozy!
> *

Huh that seems like a bug. If it deleted the file I wouldn't expect it to run the command for it...

But hey if it's faster, it's faster. 🎉 
Let's change the lint command then to only run on generated files. We don't want it to error out on user files.
