### ISSUE TITLE
Display Department ID on Project Card & Project Details

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#373]
Add the Department ID to the Project Card and to Project Details.

On the Project Card, we can put it under the Project ID.

On the Project Details page, we can put it next to the Project ID.

**Comment by frankyma** [comment]
@sethmcknight Currently we do have the deptId shown if they exist (currently they don't exist for any newly created project).

On the Project Detail view, it shows up next to the project Id
![Screen Shot 2020-08-13 at 9 37 18 AM](https://user-images.githubusercontent.com/43487134/90162033-dfc78480-dd48-11ea-92dd-a70c8879af3e.png)

On the Project card view, we currently have the logic if **department id exists, show that id only.  Otherwise show project id.  Both without label on the ids.**  @sethmcknight it sounds like that's incorrect logic (aka if both need to be visible at the same time if they exist, with labels)
![Screen Shot 2020-08-13 at 9 37 23 AM](https://user-images.githubusercontent.com/43487134/90162523-9c214a80-dd49-11ea-88ab-d587e00334e6.png)
)

**Comment by CarsonF** [comment]
Let's change the list card to show both.
