### ISSUE TITLE
Logout > While logging out on beta.cordfield.com , the front end hangs

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#434]
**Describe the bug**
logout > while loging out on `beta.cordfield.com`, the front end hangs

**Steps to Reproduce**
1.Login(user1)
2. Click on project and view the file
3. Logout the (user1)

**Expected Result**
User should be logout without front end hangs

**Actual Result**
logout > while loging out on `beta.cordfield.com`, the front end hangs
See video -https://drive.google.com/file/d/1_E4Fe__VUkknO08CHqvYfcKrKvi8jjNy/view?usp=sharing

**Comment by CarsonF** [comment]
The query for `FileVersions` is being made with an `id` of `""` which returns (throws?) an error.

Is this an Apollo problem - is the `skip` not taking effect?
Is this our problem - shouldn't this component be unmounted when logged out?

Is this error blocking normal rendering/redirect logic? I think so, but I thought query errors were returned from hook not thrown.

/cc @glassblowerscat

**Comment by glassblowerscat** [comment]
> Is this an Apollo problem - is the `skip` not taking effect?

Our skip is definitely working in my local dev environment, at least. I don't see this error in my console when I try to log it in this scenario
 
> Is this error blocking normal rendering/redirect logic? I think so, but I thought query errors were returned from hook not thrown.
We **can** return errors from the hook, but we also have (this central error handler)[https://github.com/SeedCompany/cord-field/blob/66e3924eb58a04c55804227d93ae63ee7d39f31d/src/api/ApolloProvider.tsx#L91] in our `ApolloProvider` that creates UI. So I suppose creating the snackbar could be blocking something?

In Piyush's video, there shouldn't even be a `FileVersions` component mounted, because there are no files in the table that would create one. Curious

**Comment by glassblowerscat** [comment]
I can't create a project in beta.cordfield.com to test 😐

**Comment by glassblowerscat** [comment]
> In Piyush's video, there shouldn't even be a `FileVersions` component mounted, because there are no files in the table that would create one. Curious

Duh, I forgot I refactored this so that there's always a single `FileVersion` mounted any time the `FileActionsContext` is active

**Comment by glassblowerscat** [comment]
> Is this error blocking normal rendering/redirect logic? I think so, but I thought query errors were returned from hook not thrown.

Finally reproduced this on my machine. Probably what's happening is that `client.resetStore()` is refetching the `FileVersions` query, which now no longer has a valid `id`. Source: (https://github.com/apollographql/apollo-client/issues/1195)[https://github.com/apollographql/apollo-client/issues/1195]

**Comment by CarsonF** [comment]
In that case it's related to #349 in terms of transitions between authenticated & unauthenticated states.
