### ISSUE TITLE
Location Fields

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#447]
After the Location Refactor is complete, update and integrate the Location fields on Projects and Engagements

**Comment by sethmcknight** [comment]
**Project**
- Primary Location (Single Location)
- Other Locations (0-N Locations)
- Field Region/Zone (1 Field Region)

**Intern Engagement**
- Country of Origin (Single Location)

**Comment by sethmcknight** [comment]
Blocked by cord-api-v3#937

**Comment by sethmcknight** [comment]
The issues keeping users from viewing projects and languages after the API's Location Refactor have been resolved.

We now need to hook up all the location fields on the frontend:

Projects
- [ ] `Primary Location`(a single location assigned to a Project)
- [ ] `Region` (a single Region assigned to a Project)
- [ ] `Other Locations` (0-n locations assigned to a Project)

Intern Engagement
- [ ] `Country of Origin` (a single location assigned to an Intern Engagement)

**Comment by CarsonF** [comment]
We are going to punt on `otherLocations` right now. They will need more work (on the API too) since they are a list of relations.

**Comment by CarsonF** [comment]
I removed your assignment @glassblowerscat since you had it for the breaking changes PR. Feel free to pick it back up if you are going to work it.

---


I think we want to try and combine project's primary location and region fields. They could share a `DataButton` and be separated by a `|` char. Then their dialog could show both of those fields.
