### ISSUE TITLE
BUG | Filter by Sensitivity Breaks on Load

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#488]
When filtering by Sensitivity, the page freaks out and goes to a blank screen.

Refreshing the browser page then returns the results.

<img width="1552" alt="Screen Shot 2020-09-18 at 3 31 48 PM" src="https://user-images.githubusercontent.com/7377802/93642829-63b60180-f9c4-11ea-9724-dfa246de8ccc.png">

**Comment by CarsonF** [comment]
Looks like an infinite loop involving `CheckboxesField` & `FilterButtonDialog`. I'll assign and dig in more later, if no one beats me to it.

**Comment by frankyma** [comment]
I'm throwing in the towel too.  I put `whyDidYouRender` on all the components from `ProjectList`, `FilterButtonDialog`, `ProjectFilterOptions`, and `CheckboxesField`, and I memoized the components to get rid of the messages that said rerendered because props changed but the values are the same.

but I'm not even sure if the `whyDidYouRender` messages will capture infinite rerenders before React shuts down the app.  Otherwise I can't pinpoint which component exactly is looping the renders.
