### ISSUE TITLE
Projects List | Filter by Type

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#505]
Add a Filter option to the Projects List that allows users to filter based on the Type of Project they are looking for.

(Translation, Internship)

**Comment by glassblowerscat** [comment]
@CarsonF We don't appear to support the following with our current `RadioOption` component:

![image](https://user-images.githubusercontent.com/728777/94202790-54372c80-fe8c-11ea-8cd5-a9048da9ad19.png)

That seems right, because it lines up with the conventional use of radio-type inputs. But if we just leave out the "Show All" option, the only way for the user to return to viewing both types of project is to click "Reset Filters" and lose all their other filters. How do you want to handle this? We can't use checkboxes, because the `type` filter only accepts an `enum`, not an array, so we can't allow the user to select more than 1 option here.

**Comment by CarsonF** [comment]
Looks like another case where my enum field will come in handy. Will try to wrap it up today.
