### ISSUE TITLE
Projects > Edit > Getting "TypeError: Cannot read property 'get' of null" error while clicking on the calendar

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#513]
**Describe the bug**
Projects > Edit > Getting `TypeError: Cannot read property 'get' of null` error while clicking on the calendar.

**Steps to Reproduce**
1. Login
2. Click on the Projects menu and select project
3. Click on `Start - End Button > Calendar Icon > Month`

**Expected Result**
Calendar date and month should be clickable.

**Actual Result**
 Getting `TypeError: Cannot read property 'get' of null` error while clicking on the calendar.
See video-  https://drive.google.com/file/d/1VUZ5gsVL5QvhKcnvOZkDsz6CbRhoh5X8/view?usp=drivesdk

cord-field# d9d50245

**Comment by glassblowerscat** [comment]
This is due to a bug in our current version of `material-ui/pickers` that has been fixed in the most recent alpha. Unfortunately, there are a bunch of breaking changes between alpha 8 (us) and alpha 12 (latest). These include require `material-ui` v5 alpha. @CarsonF, how do you want to handle this? We can fix the bug in the short term by always making sure the `DateField` has a non-`null` value, but that's not the ideal user experience.
