### ISSUE TITLE
BUG | Filtering by 'Only Show Cluster/Cohort Projects' and 'Only Show My Projects' at the same time doesn't work.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#527]

**Comment by glassblowerscat** [comment]
@sethmcknight I'm not totally clear on the definition of "cluster/cohort" projects, but our API refers to this filter as "onlyMultipleEngagements", so I added two engagements to an existing one of "my" projects, and both filters worked as I would have expected. Can you elaborate a little on what expected behavior you're not seeing?

**Comment by sethmcknight** [comment]
Looks like this may just be an issue with the 'My Projects' filter. Moving to project backlog for now.
