### ISSUE TITLE
Project Files | Select/Change Folder on Upload

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#554]
As a user, I would like to select the folder that a file will be stored in as I am uploading the file so that I can organize my files without having to navigate into a specific folder before uploading.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466679390) by [Unito](https://www.unito.io)

**Comment by glassblowerscat** [comment]
@sethmcknight What sort of UX did you imagine this having? I think it'd be great to offer the user the ability to drag-and-drop onto a specific folder that's currently visible in the list, because that way it's still just a single user action. If we want to give the user the ability to select any folder anywhere in the project's file hierarchy, that's going to turn uploading into a two-step process at least

**Comment by sethmcknight** [comment]
@glassblowerscat I don't know that I have a good idea of what UX would look like. We probably need to get some designs on this first.
