### ISSUE TITLE
DESIGN: Project Reports

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#774]
Current Phase  – **Design**
Some designs are in the Current file (final design) to get started on.

[Draft - Project Reports](https://www.figma.com/file/sWiPVOrIojuU8ityKQAnBP/?node-id=172%3A0)
Link – Work in progress Figma file    

[Current- Project Reports](https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/?node-id=4739%3A78706)
Link – to Current Designs

- [x] Define 
- [ ] Design 
- [ ] Review
- [ ] Prototype
- [ ] Test
- [ ] Analyze & Report
- [ ] Review 
- [ ] Design Adjustments (if necessary)

**Comment by AmyRickwartz** [comment]
Project Reporting Process.    _from Roadmap_

**Product**
CORD Field
CORD Platform
Domo

**Strategic Link**
Investor Communications

**Estimate**
Large

**Description**
Improve the Project Reporting process by standardizing the method and information that is submitted on a recurring basis. This reduces the chance of errors due to manual input and also lays the groundwork for staff no longer needing to go through Sue Akovenko as a gatekeeper to upload information.

**Requirements**
Upload multiple types of recurring reports (Progress, Narrative, Financial) 
Capturing the user who uploaded
User selects the timeframe (QTR/FY or MM/YY) covered
Name/file each item uploaded

**Comment by AmyRickwartz** [comment]
Starting work on this today.
