### ISSUE TITLE
Project > Calendar popup is not closed automatically when selecting the current date

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#790]
**Roles:** All

**Describe the bug**
Project > Calendar popup is not closed automatically when selecting the current date

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project
3. Open created project
4. Click on the `Estimated Submission Date` button and add the date

**Expected Result**
The calendar popup should be dismissed automatically on selecting a current date.

**Actual Result**
The calendar popup is not closed automatically when selecting the current date
See video - 

https://user-images.githubusercontent.com/5212585/113716476-43535780-9708-11eb-8d0b-866bd98516b4.mp4

cord-field# c914ab9a

**Comment by CarsonF** [comment]
Yeah the date picker changed their user flow. Now the current month and day are automatically set when choosing the year and month respectively. So you could say when you clicked April, today's day was set right then.

We are in a bad spot with the date picker right now. They've abandoned the current unstable version, because they moved it into the `@material-ui/core` library. However it's in the next major version, v5, which is still in development. And would require significant work for us to upgrade to. So we are essentially stuck right now. See #784 

I think I'd like to close this as a "won't fix" for two reasons. First, as I said above, there's nothing we can do so this won't get changed for probably months. Second, I believe it to be very rare that the user actually wants to select today's date. Furthermore, in the rare chance they do, it is already set and they can just click off of the popup.

What do you think @iPiyushPatel? Is that ok with you?
