### ISSUE TITLE
Change to Plan: Implement CRUD for CRs

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-field#793]
Now that API [#1768](https://github.com/SeedCompany/cord-api-v3/issues/1768) is done, refactor the work done in FE #788 to fully implement the new API. 

There should be a component to:
1. Create a CR.
2. View current CRs.
3. Select a CR to be the active CR getting updated.
4. Delete a CR.

**Comment by zkhin** [comment]
@michaelmarshall @sethmcknight 
Here are my thoughts for implementing CRUD of CRs
1. In the project detail page, if the user clicks `Change to Plan Request`, it enters CR mode (instead of opening create modal)
![image](https://user-images.githubusercontent.com/4212008/113925399-faa7a700-97b8-11eb-8009-c73dad32014e.png)
2. In the CR mode, user could change project details (right now just `project name`). When the user changes the project name, it will call creating a CR request with `Pending` status. (at that time, Backend should know that is for changing project name request)

**Comment by michaelmarshall** [comment]
Remember that there can be multiple CRs open at once. So we need a way to view the open CRs and then select one of them in order to enter the CR-mode for the correct CR.

**Comment by michaelmarshall** [comment]
@CarsonF any thoughts on how CR-mode should be implemented?

**Comment by CarsonF** [comment]
Yeah we'll store the working change id in a react context. Probably at the app/root level, so navigation to another page doesn't kick you out unless you want to. We can display current change info in a banner in the `Header` component.

We'll need to update all queries and mutations to pull from this. Though it would be better if that part could be abstracted too.
